---
title: "Queen"
author: "Hannah Valencia"
date: "11/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)

library(tm)
library(SnowballC)
library(wordcloud)
library(RColorBrewer)
library(infer)
library(janitor)
library(ggplot2)
library(spotifyr)
library(ggrepel)
library(tidyverse)
```

```{r}
Sys.setenv(SPOTIFY_CLIENT_ID = "1ce7b32e4d444e1d9df600fd87f33350")  
Sys.setenv(SPOTIFY_CLIENT_SECRET = "6709043e71214357892e9c271fe67625")  
access_token <- get_spotify_access_token()
```

```{r}
queen <- get_artist_audio_features("queen")
```

```{r}
studio_albums <- c("Queen", "Queen II", "Sheer Heart Attack", "A Night At The Opera", "A Day At The Races", "News Of The World", "Jazz", "The Game", "Flash Gordon", "Hot Space", "The Works", "A Kind Of Magic", "The Miracle", "Innuendo", "Made In Heaven")
  
  
queen <- queen %>%
  filter(album_name %in% studio_albums) %>%
  distinct(track_name, .keep_all = TRUE) %>%
  filter(!str_detect(track_name, "Remastered")) %>%
  filter(!str_detect(track_name, "Remix")) %>%
  filter(!str_detect(track_name, "A Kind Of 'A Kind Of Magic'")) %>%
  filter(!str_detect(track_name, "Doing Alright")) %>%
  filter(!str_detect(track_name, "Dreamers Ball")) %>% 
  filter(!str_detect(track_name, "Friends Will Be Friends Will Be Friends")) %>%
  filter(!str_detect(track_id, "6WjY4oKPVQ9lZaq3aJ0H5v")) %>%
  filter(!str_detect(track_name, "Good Old-Fashioned Lover Boy")) %>%
  filter(!str_detect(track_name, "Is This The World We Created...?")) %>%
  filter(!str_detect(track_id, "6hlfPqywCSczPKz1KMqfXU")) %>%
  filter(!str_detect(track_id, "6nNVF7tBApaNEU5f9modse")) %>%
  filter(!str_detect(track_name, "Modern Times Rock'n'Roll")) %>%
  filter(!str_detect(track_id, "S3PFKogVtgrMTHeuxbJJBkI")) %>%
  filter(!str_detect(track_name, "Son And Daughter")) %>%
  filter(!str_detect(track_id, "69aswOmLtNPzStgpkzFQ2c	")) %>%
  filter(!str_detect(track_name, "The Invisible Man - Extended Version")) %>%
  filter(!str_detect(track_name, "Track 13"))

write_rds(queen, "QueenAnalysis/queen.rds")
```

```{r}
a <- queen %>%
  select(track_name, album_name)
```

```{r}
queen %>%
  group_by(album_name) %>%
  ggplot(aes(x = track_name, y = danceability, color = album_name)) +
  geom_col() +
  facet_wrap(~album_name)
```
```{r}
queen %>%
  group_by(album_name) %>%
  ggplot(aes(x = track_name, y = energy, color = album_name)) +
  geom_col() +
  facet_wrap(~album_name)
```
```{r}
queen %>%
  group_by(album_name) %>%
  ggplot(aes(x = track_name, y = liveness, color = album_name)) +
  geom_col() +
  facet_wrap(~album_name)
```

```{r}
queen %>%
  group_by(album_name) %>%
  arrange(album_release_year) %>%
  count() %>%
  
  ggplot(aes(x = album_name, y = n)) +
  geom_col() +
  labs(x = "Album Name (from oldest album to most recent)", y = "Number of Tracks", title = "Number of Tracks Per Studio Album", subtitle = "How has the number of songs per album changed over the years?") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
queen %>%
  group_by(mode_name, album_name) %>%
  count() %>%
  
  ggplot(aes(x = album_name, y = n, fill = mode_name)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Key of Songs by Album", x = "Album Name", y = "Number of Songs")
```
```{r}
queen %>%
  group_by(mode_name, album_name) %>%
  count() %>%
  
  ggplot(aes(x = mode_name, y = n, fill = album_name)) +
  geom_col()
```

```{r}
queensent <- queen %>%
  select(album_name, track_name, energy, valence)
```


```{r}
queen %>%
  ggplot(aes(x = valence, y = energy, color = album_name)) +
  geom_point() +
  geom_vline(xintercept = .5) +
  geom_hline(yintercept = .5) +
  annotate("text", x = .1, y = -0.05, label = "Sad/Depressing") +
  annotate("text", x = .1, y = 1, label = "Turbulant/Angry") +
  annotate("text", x = 0.9, y = -0.05, label = "Chill/Peaceful") +
  annotate("text", x = 0.9, y = 1, label = "Happy/Joyful") +
  labs(x = "Valence", y = "Energy", title = "Song Sentiment")
```


```{r}
queen %>%
  mutate(duration_s = duration_ms/1000) %>%
  mutate(duration_m = duration_s/60) %>%
  ggplot(aes(x = track_name, y = duration_m, group = album_name, color = album_name)) +
  geom_point() +
  geom_smooth(method = 'lm', se = FALSE)
```

```{r}
ggplot(queen, aes(x = valence, y = energy, group = album_name, color = album_name)) +
            geom_point() +
            geom_smooth(method = "lm", se = FALSE) +
            geom_vline(xintercept = .5) +
            geom_hline(yintercept = .5) +
            labs(x = "Valence", y = "Energy", title = "Song Sentiment")
```












